#This file was originally generated by PyScripter's unit test wizard
import highscoringwords

class UnitTest:
    def __init__(self):
        pass

    def IsEqual(self, A, B):
        if (A != B):
            print("Test Failed")
        else:
            print("pass")


class TestHighScoringWords:

    def __init__(self):
        self.highscore = highscoringwords.HighScoringWords();
        self.UnitTest =  UnitTest();
        pass

    def tearDown(self):
        pass

    def testbuild_leaderboard_for_word_list(self):
        pass

    def testbuild_leaderboard_for_letters(self):

        pass

Test = TestHighScoringWords();
Test.testbuild_leaderboard_for_letters();

